apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime-chat-ui
  namespace: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: realtime-chat-ui
  template:
    metadata:
      labels:
        app: realtime-chat-ui
    spec:
      containers:
        - name: realtime-chat-ui
          image: realtime-chat-ui
          ports:
            - containerPort: 3000
