apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: mateuslopess/ci-sum
    newName: mateuslopess/ci-sum
    newTag: c58b625834eb8b45c0d3d3b45ba4cbc288fc5146
