apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: app
  newName: mateuslopess/realtime-chat-ui
  newTag: c58b625834eb8b45c0d3d3b45ba4cbc288fc5146
- name: mateuslopess/realtime-chat-ui
  newTag: e8e1b592cd66fb8d8a12879f0268a0724d945901
